# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.mode", 0);
user_pref("browser.cache.disk.capacity", 64000);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days", 31);
user_pref("browser.history_expire_days.mirror", 31);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://www.mobilmir.ru/");
user_pref("browser.startup.page", 0);
user_pref("dom.disable_window_move_resize", true);
user_pref("intl.charsetmenu.browser.cache", "windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_submit_insecure.show_once", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("security.warn_viewing_mixed.show_once", false);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("plugins.click_to_play", true);
