# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

//user_pref("network.proxy.ftp", "192.168.1.1");
//user_pref("network.proxy.ftp_port", 3128);
//user_pref("network.proxy.gopher", "192.168.1.1");
//user_pref("network.proxy.gopher_port", 3128);
//user_pref("network.proxy.http", "192.168.1.1");
//user_pref("network.proxy.http_port", 3128);
//user_pref("network.proxy.share_proxy_settings", true);
//user_pref("network.proxy.socks", "192.168.1.1");
//user_pref("network.proxy.socks_port", 3128);
//user_pref("network.proxy.ssl", "192.168.1.1");
//user_pref("network.proxy.ssl_port", 3128);
//user_pref("network.proxy.type", 1);
